#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2017.3 (64-bit)
#
# Filename    : mainsoc.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Dec 30 18:05:38 CET 2017
# SW Build 2018833 on Wed Oct  4 19:58:07 MDT 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved. 
#
# usage: mainsoc.sh [-help]
# usage: mainsoc.sh [-lib_map_path]
# usage: mainsoc.sh [-noclean_files]
# usage: mainsoc.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'mainsoc.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm microblaze_v10_0_4 axi_lite_ipif_v3_0_4 axi_intc_v4_1_10 xlconcat_v2_1_1 mdm_v3_2_11 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 smartconnect_v1_0 xlconstant_v1_1_3 interrupt_control_v3_1_4 axi_gpio_v2_0_16 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 axi_uartlite_v2_0_18 lmb_v10_v3_0_9 lmb_bram_if_cntlr_v4_0_13 blk_mem_gen_v8_4_0 axi_timer_v2_0_16 lib_bmg_v1_0_9 fifo_generator_v13_2_0 lib_fifo_v1_0_9 axi_ethernetlite_v3_0_12 dist_mem_gen_v8_0_12 axi_quad_spi_v3_2_13 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_14 axi_data_fifo_v2_1_13 axi_crossbar_v2_1_15)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "mainsoc.sh - Script generated by export_simulation (Vivado v2017.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work microblaze_v10_0_4 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5eb2/hdl/microblaze_v10_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_microblaze_0_0/sim/mainsoc_microblaze_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_pd.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_top.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_edge_store.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_skip_calib_tap.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_tap_base.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_cc.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_meta.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_top.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_calib_top.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_init.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_0_mem_intfc.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_0_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_col_mach.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_round_robin_arb.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_compare.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_arb_select.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_arb_mux.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_rank_cntrl.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_state.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_arb_row_col.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_rank_mach.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_mach.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_common.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_cntrl.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_rank_common.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_queue.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_mc.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_clk_ibuf.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_infrastructure.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_tempmon.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_fi_xor.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_buf.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_gen.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_top.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_rd_data.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_wr_data.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_cmd.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_or.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_and.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/mainsoc_mig_7series_0_0_mig_sim.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mig_7series_0_0/mainsoc_mig_7series_0_0/user_design/rtl/mainsoc_mig_7series_0_0.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_clk_wiz_0_0/mainsoc_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_clk_wiz_0_0/mainsoc_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_10 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/cf04/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_microblaze_0_axi_intc_0/sim/mainsoc_microblaze_0_axi_intc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_microblaze_0_xlconcat_0/sim/mainsoc_microblaze_0_xlconcat_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work mdm_v3_2_11 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/aa5e/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_mdm_1_0/sim/mainsoc_mdm_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_rst_clk_wiz_0_150M_0/sim/mainsoc_rst_clk_wiz_0_150M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/786b/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_12/sim/bd_c2f9_s00a2s_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_21/sim/bd_c2f9_s01a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/92d2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_24/sim/bd_c2f9_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/fa70/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_30/sim/bd_c2f9_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_25/sim/bd_c2f9_m00arn_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_26/sim/bd_c2f9_m00rn_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_27/sim/bd_c2f9_m00awn_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_28/sim/bd_c2f9_m00wn_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_29/sim/bd_c2f9_m00bn_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_22/sim/bd_c2f9_sarn_1.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_23/sim/bd_c2f9_srn_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/8ad6/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_18/sim/bd_c2f9_s01mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/0f5f/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_19/sim/bd_c2f9_s01tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/925a/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_20/sim/bd_c2f9_s01sic_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_13/sim/bd_c2f9_sarn_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_14/sim/bd_c2f9_srn_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_15/sim/bd_c2f9_sawn_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_16/sim/bd_c2f9_swn_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_17/sim/bd_c2f9_sbn_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_9/sim/bd_c2f9_s00mmu_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_10/sim/bd_c2f9_s00tr_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_11/sim/bd_c2f9_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/1b0c/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_4/sim/bd_c2f9_arsw_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_5/sim/bd_c2f9_rsw_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_6/sim/bd_c2f9_awsw_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_7/sim/bd_c2f9_wsw_0.sv" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_8/sim/bd_c2f9_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_0/sim/bd_c2f9_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_1/sim/bd_c2f9_psr0_0.vhd" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_2/sim/bd_c2f9_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/ip/ip_3/sim/bd_c2f9_psr_aclk1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/bd_0/sim/bd_c2f9.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_smc_0/sim/mainsoc_axi_smc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_rst_mig_7series_0_200M_0/sim/mainsoc_rst_mig_7series_0_200M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_16 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/e9c1/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_gpio_0_0/sim/mainsoc_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_gpio_1_0/sim/mainsoc_axi_gpio_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_18 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/a8a5/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_uartlite_0_0/sim/mainsoc_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/78eb/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_dlmb_v10_0/sim/mainsoc_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_ilmb_v10_0/sim/mainsoc_ilmb_v10_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_13 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/0739/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_dlmb_bram_if_cntlr_0/sim/mainsoc_dlmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_ilmb_bram_if_cntlr_0/sim/mainsoc_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/e50b/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_lmb_bram_0/sim/mainsoc_lmb_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_timer_v2_0_16 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/f3cd/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_timer_0_0/sim/mainsoc_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_bmg_v1_0_9 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/8679/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/0798/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_0 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/0798/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/0798/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_9 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/462e/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_ethernetlite_v3_0_12 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d538/hdl/axi_ethernetlite_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_ethernetlite_0_0/sim/mainsoc_axi_ethernetlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ab5e/src/rgmii_to_mii.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_rgmii_to_mii_0_0/sim/mainsoc_rgmii_to_mii_0_0.v" \
    "$ref_dir/../../../bd/mainsoc/ipshared/393f/hdl/interrupt_demo_v1_0_S_AXI.v" \
    "$ref_dir/../../../bd/mainsoc/ipshared/393f/hdl/interrupt_demo_v1_0.v" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_interrupt_demo_0_0/sim/mainsoc_interrupt_demo_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work dist_mem_gen_v8_0_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d46a/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_quad_spi_v3_2_13 $vhdlan_opts \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5786/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_quad_spi_0_0/sim/mainsoc_axi_quad_spi_0_0.vhd" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_axi_quad_spi_0_1/sim/mainsoc_axi_quad_spi_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/a259/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/74ae/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/a1b8/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/5123" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../linuxsystem.srcs/sources_1/bd/mainsoc/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mainsoc/ip/mainsoc_xbar_0/sim/mainsoc_xbar_0.v" \
    "$ref_dir/../../../bd/mainsoc/sim/mainsoc.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.mainsoc xil_defaultlib.glbl -o mainsoc_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./mainsoc_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./mainsoc.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/wachag/Projects/kintex7/linux/hw/linuxsystem/linuxsystem.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key mainsoc_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc mainsoc_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./mainsoc.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: mainsoc.sh [-help]\n\
Usage: mainsoc.sh [-lib_map_path]\n\
Usage: mainsoc.sh [-reset_run]\n\
Usage: mainsoc.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
