set_property IOSTANDARD LVCMOS33 [get_ports mdio_rtl_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio_rtl_mdio_io]
set_property PACKAGE_PIN K25 [get_ports mdio_rtl_mdc]
set_property PACKAGE_PIN K26 [get_ports mdio_rtl_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_txc]
set_property PACKAGE_PIN N24 [get_ports {RGMII_0_rd[3]}]
set_property PACKAGE_PIN N26 [get_ports {RGMII_0_rd[2]}]
set_property PACKAGE_PIN N23 [get_ports {RGMII_0_rd[1]}]
set_property PACKAGE_PIN P24 [get_ports {RGMII_0_rd[0]}]
set_property PACKAGE_PIN P25 [get_ports {RGMII_0_td[3]}]
set_property PACKAGE_PIN P26 [get_ports {RGMII_0_td[2]}]
set_property PACKAGE_PIN R26 [get_ports {RGMII_0_td[1]}]
set_property PACKAGE_PIN T25 [get_ports {RGMII_0_td[0]}]
set_property PACKAGE_PIN M26 [get_ports RGMII_0_rx_ctl]
set_property PACKAGE_PIN P23 [get_ports RGMII_0_rxc]
set_property PACKAGE_PIN T24 [get_ports RGMII_0_tx_ctl]
set_property PACKAGE_PIN R25 [get_ports RGMII_0_txc]
set_property PACKAGE_PIN D13 [get_ports sdcard_csn]
set_property PACKAGE_PIN H14 [get_ports sdcard_miso]
set_property PACKAGE_PIN B14 [get_ports sdcard_mosi]
set_property PACKAGE_PIN F13 [get_ports sdcard_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports sdcard_csn]
set_property IOSTANDARD LVCMOS33 [get_ports sdcard_miso]
set_property IOSTANDARD LVCMOS33 [get_ports sdcard_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports sdcard_sclk]

set_property IOSTANDARD LVCMOS33 [get_ports {flash_spi_ss_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports flash_spi_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports flash_spi_io1_io]
set_property PACKAGE_PIN C23 [get_ports {flash_spi_ss_io[0]}]
set_property PACKAGE_PIN B24 [get_ports flash_spi_io0_io]
set_property PACKAGE_PIN A25 [get_ports flash_spi_io1_io]



set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN DIV-1 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports flash_spi_io2_io]
set_property IOSTANDARD LVCMOS33 [get_ports flash_spi_io3_io]
set_property PACKAGE_PIN B22 [get_ports flash_spi_io2_io]
set_property PACKAGE_PIN A22 [get_ports flash_spi_io3_io]

create_clock -period 40.000 -name rgmii_rx_clk -waveform {0.000 20.000} [get_ports RGMII_0_RXC]

set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_24bits_tri_o[0]}]
set_property PACKAGE_PIN C19 [get_ports {led_24bits_tri_o[15]}]
set_property PACKAGE_PIN D19 [get_ports {led_24bits_tri_o[14]}]
set_property PACKAGE_PIN C17 [get_ports {led_24bits_tri_o[13]}]
set_property PACKAGE_PIN D16 [get_ports {led_24bits_tri_o[12]}]
set_property PACKAGE_PIN D14 [get_ports {led_24bits_tri_o[11]}]
set_property PACKAGE_PIN G19 [get_ports {led_24bits_tri_o[10]}]
set_property PACKAGE_PIN E18 [get_ports {led_24bits_tri_o[9]}]
set_property PACKAGE_PIN G17 [get_ports {led_24bits_tri_o[8]}]
set_property PACKAGE_PIN D20 [get_ports {led_24bits_tri_o[7]}]
set_property PACKAGE_PIN B19 [get_ports {led_24bits_tri_o[6]}]
set_property PACKAGE_PIN B17 [get_ports {led_24bits_tri_o[5]}]
set_property PACKAGE_PIN B16 [get_ports {led_24bits_tri_o[4]}]
set_property PACKAGE_PIN B15 [get_ports {led_24bits_tri_o[3]}]
set_property PACKAGE_PIN F20 [get_ports {led_24bits_tri_o[2]}]
set_property PACKAGE_PIN F18 [get_ports {led_24bits_tri_o[1]}]
set_property PACKAGE_PIN F17 [get_ports {led_24bits_tri_o[0]}]
set_property PACKAGE_PIN C18 [get_ports {leds_0[7]}]
set_property PACKAGE_PIN D18 [get_ports {leds_0[6]}]
set_property PACKAGE_PIN C16 [get_ports {leds_0[5]}]
set_property PACKAGE_PIN D15 [get_ports {leds_0[4]}]
set_property PACKAGE_PIN C14 [get_ports {leds_0[3]}]
set_property PACKAGE_PIN F19 [get_ports {leds_0[2]}]
set_property PACKAGE_PIN E17 [get_ports {leds_0[1]}]
set_property PACKAGE_PIN E16 [get_ports {leds_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[0]}]
